language: node_js
node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g lerna
  - npm install -g greenkeeper-lockfile

install:
  - yarn cache clean
  - yarn install

script:
  - yarn test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn multi-semantic-release --execasync
    # - yarn lerna run build && yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo" && node -e "require('semantic-release-monorepo-hooks').hookAfterAll()"
  on:
    branch: master
